apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-web
  labels:
    app: dev-web
spec:
  replicas: 4
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: dev-web
  template:
    metadata:
      labels:
        app: dev-web
    spec:
      containers:
      - name: devops-web
        image: bohdanmatiuk/node-front:1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: devops-web-config
              key: PORT
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: devops-web-config
              key: API_HOST

---
apiVersion: v1
kind: Service
metadata:
  name: devops-web
spec:
  selector:
    app: devops-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  